### PR TITLE
Updated the farmland flow image

### PR DESCRIPTION
**Pull request by Wulingoh**
Test plan: 
For screen resolution over 1920 X 1080p above:
1. Go to this [link](https://docs.centrapay.com/connections/farmlands).
2. Scroll to Overview
3. Image is rendered with clarity and words are readable.  
4. Image position is at the centre of page within the Overview block
5. Image size is 450 × 626 pixels

For Mobile Android and Iphone: 
1.  Go to this [link](https://docs.centrapay.com/connections/farmlands).
2. Scroll to Overview
3. Image is rendered with clarity and words are readable.  
4. Image position is aligned with Overview title.
5. Image size is 450 × 626 pixels

Note: Review each test plan for Firefox, Chrome, Safari and Edge.

Screenshot 2023-02-02 at 11 23 08 AM
Screenshot 2023-02-02 at 11 23 33 AM

### CODE REVIEW

**Review by tom-blake — APPROVED** [review]

**Comment by tom-blake** [comment]
@Wulingoh Please add a test plan to this PR as discussed ❤️

**Comment by Wulingoh** [comment]
@tom-blake Added a test plan for each browser engine including mobile.

**Review by AndyClifford — APPROVED** [review]

**Review by Ray2126 — APPROVED** [review]

**Comment by Wulingoh** [comment]
Updated my test plan with more detail. Please review it.😀 Thanks

**Comment by AndyClifford** [comment]
Nice @Wulingoh

**Pull request merged**
