### PR TITLE
Fix auth table

### PR DESCRIPTION
**Pull request by alexBinns**
This PR fixes the auth table that wasn't able to be scrolled horizontially on mobile. The Marcdoc table is squashed into the page but is scrollable if you zoom in.

This is also based of @AndyClifford's [PR](https://github.com/centrapay/centrapay-docs/pull/803/files) so I can use the code component.

### CODE REVIEW

**Comment by MeganSteenkamp** [comment]
@alexBinns do you have screenshots of the fixed table? I pulled this locally but it looks the same as the current MDX one 🤨

**Comment by MeganSteenkamp** [comment]
@alexBinns do you have a screenshot on mobile of the fixed table? I pulled locally and it looked the same 🤠

**Comment by alexBinns** [comment]
> @alexBinns do you have a screenshot on mobile of the fixed table? I pulled locally and it looked the same 🤠

What browser are you using? I tried firefox and safari.

**Comment by MeganSteenkamp** [comment]
> > @alexBinns do you have a screenshot on mobile of the fixed table? I pulled locally and it looked the same 🤠
> 
> What browser are you using? I tried firefox and safari.

Chrome

**Comment by MeganSteenkamp** [comment]
@alexBinns I think we can close this one 🙌

**Pull request closed without merging**
